<?php // pages/exam-schedule.php ?>
<section id="exam-schedule" class="page-content">
    <h2 class="page-title"><i class="fas fa-calendar-check"></i> Exam Schedule</h2>
    <div class="exam-tabs">
        <button class="exam-tab active" data-exam-type="quiz">Quizzes</button>
        <button class="exam-tab" data-exam-type="midterm">Midterm Exams</button>
        <button class="exam-tab" data-exam-type="final">Final Exams</button>
    </div>
    <div id="quiz-exams" class="exam-content active"><h3>Upcoming Quizzes - Spring 2023-2024</h3><div class="exam-item"><h4>CSE 3205 - Software Engineering - Quiz 2</h4><p><i class="fas fa-calendar-day"></i> Date: April 02, 2024</p><p><i class="fas fa-clock"></i> Time: 10:00 AM (During class)</p><p><i class="fas fa-map-marker-alt"></i> Room: D-502</p><p><i class="fas fa-book-reader"></i> Syllabus: Chapter 3, 4</p></div><div class="exam-item"><h4>MAT 3109 - Numerical Methods - Quiz 1</h4><p><i class="fas fa-calendar-day"></i> Date: April 05, 2024</p><p><i class="fas fa-clock"></i> Time: 09:00 AM (During class)</p><p><i class="fas fa-map-marker-alt"></i> Room: B-102</p><p><i class="fas fa-book-reader"></i> Syllabus: Root Finding Methods</p></div></div>
    <div id="midterm-exams" class="exam-content"><h3>Midterm Examination Schedule - Spring 2023-2024</h3><div class="exam-item"><h4>CSE 3107 - Database Systems</h4><p><i class="fas fa-calendar-day"></i> Date: April 10, 2024 (Sunday)</p><p><i class="fas fa-clock"></i> Time: 12:00 PM - 01:30 PM</p><p><i class="fas fa-map-marker-alt"></i> Room: C-303</p></div><div class="exam-item"><h4>CSE 3205 - Software Engineering</h4><p><i class="fas fa-calendar-day"></i> Date: April 11, 2024 (Tuesday)</p><p><i class="fas fa-clock"></i> Time: 10:00 AM - 11:30 AM</p><p><i class="fas fa-map-marker-alt"></i> Room: D-502</p></div><div class="exam-item"><h4>PHY 1101 - Physics I</h4><p><i class="fas fa-calendar-day"></i> Date: April 12, 2024 (Wednesday)</p><p><i class="fas fa-clock"></i> Time: 02:00 PM - 03:30 PM</p><p><i class="fas fa-map-marker-alt"></i> Room: A-201 (Annex 2)</p></div></div>
    <div id="final-exams" class="exam-content"><h3>Final Examination Schedule - Spring 2023-2024</h3><p style="text-align: center; padding: 1rem; background-color: #fff3cd; border-radius: var(--border-radius); color: #856404;"><i class="fas fa-info-circle"></i> Final exam schedule for Spring 2023-2024 will be published around <strong>May 15, 2024</strong>. Please check back later.</p><h4 style="margin-top: 2rem; color: var(--primary-dark);">Reference: Fall 2022-2023 Final Schedule</h4><div class="exam-item"><h4>CSE 2203 - Data Structures</h4><p><i class="fas fa-calendar-day"></i> Date: December 18, 2023 (Monday)</p><p><i class="fas fa-clock"></i> Time: 09:00 AM - 11:00 AM</p><p><i class="fas fa-map-marker-alt"></i> Auditorium</p></div><div class="exam-item"><h4>MAT 2107 - Probability & Statistics</h4><p><i class="fas fa-calendar-day"></i> Date: December 20, 2023 (Wednesday)</p><p><i class="fas fa-clock"></i> Time: 01:00 PM - 03:00 PM</p><p><i class="fas fa-map-marker-alt"></i> Room: D-Building, Floor 4</p></div></div>
</section>